### ISSUE TITLE
Research for related system about the topic

### ISSUE THREAD

**Issue by catherineunciano** [IT3A-2016/Paper-Icebergs#19]

**Comment by giomigueltada** [comment]
Time Free Innovations
TimeFree is a virtual queuing solutions company that helps businesses improve customer queuing in their stores, thus improving customer loyalty and customer service, and give business owners and managers access to actionable data to streamline store operations for better efficiency and enhance staff productivity.

QMobile
QMobile is a virtual queuing aggregator mobile app that enables end-users to join a queue before arriving to the store.
Offers convenience and mobility to end-users for customer queing
Serves as another customer channel to boost the digital footprint of a business
Alerts end-users regarding their position in the queue
Offers businesses a chance to cross-sell to customers from other industries 

QApps
Enables businesses to effectively manage their customer queue.
Sends text message alerts to customers if their turn is near.
Easy to use applications for the tellers/frontliners and store
managers/business owners.
Cloud-based architecture running on Microsoft Azure ensures data are regularly backed up
Easy to setup application. No need for special hardware. All you need is a browser and internet connection.
Enables business owners and store managers to track staff
productivity and efficiency and other important metrics to
improve business operations.

**Comment by catherineunciano** [comment]
Queuing System Using Smart Card or Barcode Technology

Queuing System Using Smart Card or Barcode Technology develops to create a well-organize line-up of the students in their every transaction to the college tellers. The said institution uses the very common sequence that may see in our everyday life.

The proposed system entitled Queuing System Using Smart Card or Barcode Technology can make the teller faster in their works because the said system can manipulate or handle the students in the way that they don’t have to personally knock on the teller’s window just to give their names and transact their school payments. This is truly that the Queuing System Using Smart Card or Barcode Technology gives improvement and the processing will make less time and effort to the college tellers in the payments operation.

PROJECT CONTEXT

Queuing System Using Smart Card or Barcode Technology is a system that can manipulate in monitoring the priority of the teller to the students during examinations and enrollments. It may be easier to the students to process their payments by using such technology. Identification cards of the new students has now a barcode that is very applicable for the proposed system for it uses a barcode reader that the teller will not waste his/her time asking whose next and by also asking their identity. In the proposed system, the new identification card is very useful, for it has already a barcode at the back. Precisely, the proposed system is very useful for the operation of monitoring the fairness line-up of every student to the teller.

PURPOSE AND DESCRIPTION

Queuing System Using Smart Card or Barcode Technology can help the students enhance their knowledge and capabilities to interact to the modern environment. The said system can help the users to be interactive in their works. Transactions of the assessments were already systemized but still there is another problem. It is been consider that you must line-up first before you can do transactions to the tellers especially when examinations and enrollments approaching.

Queuing System Using Smart Card or Barcode Technology is a system which basically facilitates the well-organize line-up system of every student’s transaction to the tellers. It specify the formal processing of the students for the reason that other students that is not in the line-up just got first to transact with the tellers. Queuing System Using Smart Card or Barcode Technology is one way to solve this unorganized system.

OBJECTIVES

To provide a better and easy process of every student’s transactions
Well-organize manipulation of student’s line-up
Fairness of every student during releasing of permits for examination and paying their payments.
SCOPE AND LIMITATIONS

This study focuses on the faster transactions of every client of tellers. The system is focusing on the better and fairness student’s line-up in every examinations and enrollments. It manipulates the well-organize processing of there every assessments payment for the reason that not all the students were honest in terms of their behaviors.

Queuing System Using Smart Card or Barcode Technology is usable by swiping the student’s identification cards in the barcode reader device. The system is capable for the up-coming years because each of the identifications cards has it’s already a barcode.

The effectiveness of the study limits only on the swiping of every student’s identification cards to the barcode reader that can be seen outside the teller’s window before they can process their school payments. The proposed system was designed to develop the current teller’s process.

SIGNIFICANT OF THE STUDY

The Queuing System Using Smart Card or Barcode Technology will be a great help to the following entity

Students/Parents
Tellers
Administrators
PROCESS FLOW

The students or the one that will conduct a transaction in the cashier will swipe his or her id in the scanner, information associated with id will be sent to the tellers system. They just have to wait until their name is called.
The teller will then receive the information and conduct a transaction.
This is a first come first serve system, which means the first to swipe is the first to serve.

http://www.inettutor.com/source-code/queuing-system-using-smart-card-or-barcode-technology/

![image](https://zube.io/files/IT3A-2016/7e60c1c740cbd52049db9c8ced327dd7.png)

**Comment by catherineunciano** [comment]
This is a must view: https://www.youtube.com/watch?v=8slbQyJH980

**Comment by catherineunciano** [comment]
Teller Automated Queuing Numbering System
http://tesear.blogspot.com/2014/08/teller-automated-queuing-numbering.html

![image](https://zube.io/files/IT3A-2016/9cb9354aa959fdcb6ecb7d29aa0c5568.png)

![image](https://zube.io/files/IT3A-2016/a438c6d9b5cd37f3c072ab1556aba40c.png)

![image](https://zube.io/files/IT3A-2016/3d3a9958c1aaac951e5dd4e8c28176d5.png)

![image](https://zube.io/files/IT3A-2016/79041ff26438eb0de3d005df94c3c1bf.png)

![image](https://zube.io/files/IT3A-2016/a550d326462cecf064077ef24e0961b8.png)

**Comment by catherineunciano** [comment]
Thesis Links: 
https://etd.auburn.edu/bitstream/handle/10415/74/GOSHA_KINNIS_25.pdf?sequence=1
https://www.theseus.fi/bitstream/handle/10024/51491/Bernard%20Kakeng%20thesis.pdf?sequence=1
http://www.academia.edu/9845472/Our_Thesis_with_my_group

Holds references:
https://books.google.com.ph/books?id=tcoj3oNAAMsC&pg=PA247&lpg=PA247&dq=Information+technology+thesis+queueing+system&source=bl&ots=JWHmsg_U9k&sig=bSAIj8jMmepE0XO0YaZrZHKejTs&hl=en&sa=X&ved=0ahUKEwiq96z9mPXRAhWKHpQKHYu8CKsQ6AEIOzAE#v=onepage&q=Information%20technology%20thesis%20queueing%20system&f=false
