### ISSUE TITLE
Research about SMS Notification using PHP & JavaScript

### ISSUE THREAD

**Issue by catherineunciano** [IT3A-2016/Paper-Icebergs#20]

**Comment by Nhelie** [comment]
link: https://code.tutsplus.com/tutorials/how-to-send-text-messages-with-php--net-17693
link: http://www.developphp.com/video/PHP/Send-SMS-Text-Messages-to-Mobile-Phone-PHP-Tutorial

 <?php
/* watch the video for detailed instructions */
$to = "5555555555@vtext.com";
$from = "xxxx@yourdomain.com";
$message = "This is a text message\nNew line...";
$headers = "From: $from\n";
mail($to, '', $message, $headers);
?>

**Comment by catherineunciano** [comment]
https://davidwalsh.name/send-text-message

Phone companies have internal lookups for phone carriers but developers like you and I don't get access to them, so knowing the carrier is  a must.  To send a text message, you email {phoneNumber}@{carrierDomain}.

The PHP
PHP's provided method for sending emails is the mail function.  Its usage is quite simple:

bool mail ( string $to , string $subject , string $message [, string $additional_headers [, string $additional_parameters ]] )
Using the mail function and the text message email format, sending a text message is as easy as:

// Call Jenny
mail("5558675309@txt.att.net", "", "Your packaged has arrived!", "From: David Walsh <david@davidwalsh.name>\r\n");
Note that no subject line is provided, and more importantly, a FROM header is within the last parameter so that the recipient knows where the text message has been sent from.

**Comment by catherineunciano** [comment]
https://www.twilio.com/blog/2014/04/add-sms-to-your-web-app-in-4-lines-of-code.html

Hi there, my name is Jarod Reyes and I’m the Technical Content Producer at Twilio. In this post I’d like to quickly show you how easy it is to add SMS to your web app then give you a more in-depth look at how Twilio works as well as some more robust use-cases for SMS.

This post was inspired by a conversation I had with a friend shortly after joining Twilio. We were talking about API’s when he nonchalantly explained that he himself used Twilio to send SMS notifications from his web app. As proof he then turned his laptop around to face me and pointed to the “four lines of code [he] added” to enable SMS.

Certainly it is not always that simple. Some of our biggest customers have built entire businesses around the Twilio Platform, but everyone has to start somewhere and in my opinion these four lines of code are the place to start.

So without further adieu, I present the four lines needed to send an SMS from your web app:

Send Message - PHPPHP

<?php 
require_once('/path/to/twilio-php/Services/Twilio.php');
$client = new Services_Twilio("{{ sid }}", "{{ auth_token }}");
$client->account->messages->sendMessage("+15558675309", "+12125552368", "There’s something strange in my neighborhood. I don’t know who to call. Send help!"; ?>
1
2
3
4
<?php 
require_once('/path/to/twilio-php/Services/Twilio.php');
$client = new Services_Twilio("{{ sid }}", "{{ auth_token }}");
$client->account->messages->sendMessage("+15558675309", "+12125552368", "There’s something strange in my neighborhood. I don’t know who to call. Send help!"; ?>
Or how about Ruby:

Send Message - RubyRuby

require 'twilio-ruby'
@client = Twilio::REST::Client.new '{{ sid }}', '{{ auth_token }}'
message = @client.account.messages.create(:body => "I’m tired of having my arms cut off by snow-blowers. Please help Mr. hmmm… I forgot your name.", :to => "+16365553226", :from => "+15558675309")
puts message.to
1
2
3
4
require 'twilio-ruby'
@client = Twilio::REST::Client.new '{{ sid }}', '{{ auth_token }}'
message = @client.account.messages.create(:body => "I’m tired of having my arms cut off by snow-blowers. Please help Mr. hmmm… I forgot your name.", :to => "+16365553226", :from => "+15558675309")
puts message.to
To see more awesome examples including node.js, python, C# or java visit the Twilio docs.

So now that we’ve gotten that out of the way, let’s quickly discuss how Twilio accomplishes this task.

**Comment by catherineunciano** [comment]
https://www.sitepoint.com/implement-two-way-sms-with-php/

Implement Two-Way SMS with PHP
Two-Way SMS Life Cycle
The life cycle of two-way SMS can be divided into 4 main steps as shown below:



User sends request to SMS gateway
SMS gateway forwards request to application server
Application server processes request and responds to SMS gateway
SMS gateway forwards request back to user
Step 1 – User to SMS Gateway
The user initiates the conversation by sending an SMS message to the gateway. Initially it has to go through user’s mobile service provider. This part is not important to us since it is within the domain of the local service provider. Through the local service provider the message is received by the the SMS gateway.

The user obviously needs a specific number to send his messages to. You can use either shortcodes or dedicated long numbers (DID) specific to your application for two-way communication. These numbers are provided by SMS gateways, and normally you need to purchase these numbers.

A dedicated long number is a standard phone number, like +94112367899. A shortcode is a 4 – 6-digit code. Each have their own pros and cons:

Shortcodes are easier to remember than dedicated long numbers.
Dedicated numbers can be used globally while shortcodes are normally limited to a single service provider in a given country.
Dedicated long numbers can process a larger number of messages for a given time compared to shortcode numbers.
The choice whether to use a shortcode or dedicated long number is ultimately up to you.

Once the SMS is received by the gateway, it should be routed to the application for processing. Before the routing the message, the gateway needs to do two things:

Prepare the message data in a way that application can understand
Map an application URL to the dedicated long number or shortcode
Each gateway has its own methods for transferring data to the application server, though XML or SOAP over an HTTP connection are generally the most popular. The gateway should provide some sort of API documentation for which ever method is used.

The application developer has to create a specific entry point in the system to handle messages received from the gateway; this is called the application URL. The process of mapping application URLs to the dedicated number or shortcode varies from one gateway to another. Some allow the configuration directly through the user account interface, such as Clickatell does. If this option isn’t available, we have to contact the technical support resource for the gateway and provide them with the application URL to be configured.

Stage 2 – SMS Gateway to Application Server
The application owner then has to decide how to receive the data from the gateway. Clickatell allows you to specify this method inside the user account. If it’s not available, again you’ll need to contact the technical team of the particular gateway.

The following code example shows you how Clickatell sends the data via the HTTP GET method and now you can receive it. Other gateways will provide a similar method as well.

https://www.example.com/sms/sms.php?api_id=12345&from=279991235642&to=27123456789&timestamp=2008-08-0609:43:50&text=Hereisthe%20messagetext&charset=ISO-8859-1&udh=&moMsgId=b2aee337abd962489b123fda9c3480fa
<?php
$fromNo = $_GET["from"];
$toNo = $_GET["to"];
$message = $_GET["text"];
$msgID = $_GET["moMsgId"];

// Process the user command and generate output
...
And here’s an example where the data is POSTed as an XML document.

<?xml version="1.0"?>
<clickmo>
  <api_id>xxx</api_id>
  <moMsgId>fa6ba35b330ce1bc7e2008e5d92d57aa</moMsgId>
  <from>handset_number_here</from>
  <to>mo_number_here</to>
  <timestamp>2007-02-26 14:36:50</timestamp>
  <text>xxx</text>
  <charset>ISO-8859-1</charset>
  <udh></udh>
</clickmo>
<?php
$data = $_POST["data"];

$xmlDoc = new DOMDocument();
$xmlDoc->loadXML($data);

$fromNo = $xmlDoc->getElementsByTagName("from");
$fromNo = $fromNo->item(0)->nodeValue;

$toNo = $xmlDoc->getElementsByTagName("to");
$toNo = $toNo->item(0)->nodeValue;

$message = $xmlDoc->getElementsByTagName("text");
$message = $message->item(0)->nodeValue;

// Process User Message and Generate Response
...
The application needs to capture the incoming data using one of the available methods and process the user’s commands. In a simple scenario where user’s message is less than 160 characters, this code works perfectly. But what will happen if the message is more than 160 characters?

Let’s assume a television station starts an advertising campaign where users can send advertisements as SMS. Once the SMS is sent, the user will receive a time period from the server where the advertisement will be displayed. Advertisements are text only and will be displayed on the bottom of the screen. Let’s also assume we have the predefined format for sending messages as shown below.

advertisement sports title your advertisement title message content of your advertisement
All of the content in the message appears as value pairs. advertisement will be the label and sports will be the value representing the advertising category. Then, title is the next label and its value will be the heading of the advertisement. message is the final label and will be the content the user wants to display in the advertisement.

Depending on the length of the title and message, this SMS can have more than 160 characters. Every time a lengthy message is received, the gateway splits it into multiple 160-character parts. But still we have to handle those 2 parts as a single message.

If we use the previous code examples to parse the messages, parts 1 and 2 of the same message would be handled as two different messages. And since both parts do not have the full command, the application would send back an error to the user. UDH is the solution to this problem.

What is UDH?
UDH stands for User Data Header. When we send a lengthy message, the sending device (mobile phone) splits the message and sends it as separate messages. UDH values will be assigned to beginning of each message part so that receiving device can identify them as belonging to a single message and recombine them.

The UDH values for the earlier scenario would look like this:

Part 1 - 05 00 03 CC 02 01
Part 2 - 05 00 03 CC 02 02
The last two hex values will be the most important values in the UDH. The second to last digit is 02 in the above codes and defines the number of parts in the message. So, this message was split into two parts. If three parts were available, then this value should be 03, and so on. The next digit defines the part number of the message. 01 means it’s the first part, 02 mean the second part, etc.

Now we have what we need to know to process lengthier messages that were split up into multiple parts.

<?php
$fromNo = $_GET["from"];
$toNo = $_GET["to"];
$message = $_GET["text"];
$msgID = $_GET["moMsgId"];
$udh = $_GET["udh"];

$total = 1;
$count = 1;
if ($udh) {
    $tmp = str_split($udh, 2);
    $total = hexdec($tmp[4]);
    $count = hexdec($tmp[5]);
}

if ($count != $total) {
    // Save the message fragment in database
    saveMessagePart($db, $from, $message, $udh);
}
else if ($total != 1) {
	$prevParts = getMessageParts($db, $from);
	$message = $prevParts . $message;
}

// process $message
...
Now that we can handle a full message and act on it, this completes this stage of the request cycle. The next two stages show how the response is sent back to the user through the gateway.

Stage 3 and 4 – Application Server to SMS Gateway, Gateway to User
In the previous stage I explained the process up to receiving messages from the gateway and processing it within your application. Once the request is processed and the response is generated, we need to send it back to the gateway.

Generally, SMS gateways provide a callback URL for us to pass the response data. You usually have to provide the receiver’s number, the sender’s number, the message content, and some sort of authentication information. The exact parameters will vary according to the gateway, but for Clickatell they are to, from, text, and api_id, username, and password.

<?php
$message = array(
    "to" => 942288345,
    "from" => 944488345,
    "text" => "sample message",
    "api_id" => API_KEY,
    "user" => "myUsername",
    "password" => "secret"
);

$apiUrl = "http://api.clickatell.com/http/sendmsg?";
foreach ($message as $parameter => $value ) {
    $apiUrl .= $parameter . "=" . urlencode($value) . "&";
}
$apiUrl = rtrim($apiUrl, "&");

$ch = curl_init();
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
curl_setopt($ch, CURLOPT_URL, $apiUrl);

curl_exec($ch);
curl_close($ch);
The code sample above first encodes all of the parameters using urlencode() and appends them to the API’s callback URL. Then, we initialize a cURL request and call the URL. The response message has now been sent to the gateway, which concludes step 3.

Step 4 is straightforward and we don’t have to do anything in this part of the process. The gateway is responsible for sending all the messages in the correct order to the users mobile.

**Comment by catherineunciano** [comment]
http://www.webdeveloper.com/forum/showthread.php?170285-Send-SMS-(text-messages)-via-PHP

Send SMS (text messages) via PHP
The form:
Code:
<form id="sms" name="sms" method="post" action="scripts/send_sms.php">
<table width="400">
  <tr>
    <td align="right" valign="top">From:</td>
    <td align="left"><input name="from" type="text" id="from" size="30" /></td>
  </tr>
  <tr>
    <td align="right" valign="top">To:</td>
    <td align="left"><input name="to" type="text" id="to" size="30" /></td>
  </tr>
  <tr>
    <td align="right" valign="top">Carrier:</td>
    <td align="left"><select name="carrier" id="carrier">
      <option value="verizon">Verizon</option>
      <option value="tmobile">T-Mobile</option>
	  <option value="sprint">Sprint</option>
	  <option value="att">AT&amp;T</option>
	  <option value="virgin">Virgin Mobile</option>
    </select></td>
  </tr>
  <tr>
    <td align="right" valign="top">Message:</td>
    <td align="left"><textarea name="message" cols="40" rows="5" id="message"></textarea></td>
  </tr>
  <tr>
    <td colspan="2" align="right"><input type="submit" name="Submit" value="Submit" /></td>
    </tr>
</table>
</form>
The handler:
Code:
<?php
$from = $_POST['from'];
$to = $_POST['to'];
$carrier = $_POST['carrier'];
$message = stripslashes($_POST['message']);

if ((empty($from)) || (empty($to)) || (empty($message))) {
header ("Location: sms_error.php");
}

else if ($carrier == "verizon") {
$formatted_number = $to."@vtext.com";
mail("$formatted_number", "SMS", "$message"); 
// Currently, the subject is set to "SMS". Feel free to change this.

header ("Location: sms_success.php");
}

else if ($carrier == "tmobile") {
$formatted_number = $to."@tomomail.net";
mail("$formatted_number", "SMS", "$message");

header ("Location: sms_success.php");
}

else if ($carrier == "sprint") {
$formatted_number = $to."@messaging.sprintpcs.com";
mail("$formatted_number", "SMS", "$message");

header ("Location: sms_success.php");
}

else if ($carrier == "att") {
$formatted_number = $to."@txt.att.net";
mail("$formatted_number", "SMS", "$message");
header ("Location: sms_success.php");
}

else if ($carrier == "virgin") {
$formatted_number = $to."@vmobl.com";
mail("$formatted_number", "SMS", "$message");

header ("Location: sms_success.php");
}
?>
Sending a text message to a cell phone through PHP is just a matter of appending the correct suffix to the number and using the mail() function. If you want to add more carriers, go here and find the carrier you are looking for. If you do not know the carrier (ie. if you want to add a "not sure" option to the pulldown menu), add @teleflip.com as the suffix. The phone numbers must be 10 digits long (XXX-XXX-XXXX).

**Comment by catherineunciano** [comment]
http://www.ozekisms.com/index.php?owpn=246

Step 1: Create the HTML form 
In the smssend.html file, you create the form that requests the sms data. The Internet user fills in the necessaries. The head element includes the smssend.js file. Label and textbox pairs will be displayed. Labels identify the requested data for the Internet user, and they will type it in textboxes. The user will be asked to fill in the Recipient and Message text fields. A div element is used to inform the Internet user about error(s) or result(s) of sending the message. At first, the div element will be invisible (it will be set in the smssend.js file). If the Internet user clicks Send image, the sendRequest() function will be run. 

smssend.html
<html>
    <head>
        <title>Ozeki NG SMS Gateway Message Sending Example</title>

        <script src="smssend.js"></script>
    </head>

    <body>
        <form>
        <table align="center">
            <tr>
                <td colspan="2" align="center">
                    <b>Compose a message</b>
                    <br><br>
                </td>
            </tr>
            <tr>
                <td>
                    Recipient:
                </td>
                <td>
                    <input type="text" id="recipient" name="recipient" size="40">
                </td>
            </tr>
            <tr>
                <td valign="top">
                    Message text:
                </td>
                <td>
                    <textarea id="messagetext" name="messagetext" rows="3" cols="40"></textarea>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <img src="send.gif" onclick="sendRequest();">
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <br /><div id="responseText" name="responseText" style="color:red;"></div>
                </td>
            </tr>
        </table>
    </form>
    </body>
</html>
            



Step 2: Processing data coming from the HTML form 
After filling in the fields and clicking the Send button (image), the AJAX receives the information about the fields. In the smssend.js file, the function GetXmlHttpObject() will run in function sendRequest(). You will create an XMLHttpRequest object in it, which will send and receive data. 

smssend.js
...
function GetXmlHttpObject()
{
    var xmlHttp = null;
    try
    {
        // Firefox, Opera 8.0+, Safari
        xmlHttp = new XMLHttpRequest();
    }
    catch (e)
    {
        // Internet Explorer
        try
        {
            xmlHttp = new ActiveXObject("Msxml2.XMLHTTP");
        }
        catch (e)
        {
            xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
        }
    }
    return xmlHttp;
}
...
            


If you click the Send image function, sendRequest() will run. At the beginning of the function, the XMLHttpRequest object is created, and you check the data of the textbox fields. The Recipient box is mandatory. If it is empty, the processing will be aborted, and the Internet user will be informed by a window containing the error message. If the checking is successful, you will create the URL that will tell the Ozeki NG - SMS Gateway Server the requested information. We need the following: the URL of the computer running Ozeki NG - SMS Gateway Server, the default URL is http://127.0.0.1 (127.0.0.1 means that Ozeki NG - SMS Gateway Server is installed on the same computer on which the AJAX script is running), the port number on which the server listens, the username, which is authorized to log in to the Ozeki NG - SMS Gateway Server and to send messages (the default username is admin), the user's password (the default is abc123), the message type (the default is SMS:TEXT), the recipient and the message data. The following values must be URL-encoded: username, password, recipient and message data. 

smssend.js
...
function sendRequest()
{
    xmlHttp = GetXmlHttpObject(); //create the object with which we will send
                                  //the request and receive the response

    if (xmlHttp == null)
    {
        alert ("Your browser does not support AJAX!");
        return;
    }

    if (document.getElementById("recipient").value == "")
    {//we must fill in field recipient!
        document.getElementById("responseText").innerHTML = "";
        alert ("Recipient field is mandatory!");
        return;
    }


    var createdURL = ""; //this will be sent to Ozeki NG SMS Gateway Server...
    var parameters = ""; //...together with the parameters
    var ozSURL = "http://127.0.0.1"; //URL where Ozeki NG SMS Gateway Server is
    running
    var ozSPort = "9501"; //Port number on which Ozeki NG SMS Gateway Server is
    listening to
    var ozUsername = encodeURIComponent("admin"); //Username who can log in to
                                                  //Ozeki NG SMS Gateway Server
    var ozPassw = encodeURIComponent("abc123"); //the user's password
    var ozMessageType = "SMS:TEXT"; //type of the message
    var ozRecipient = encodeURIComponent(document.getElementById("recipient").value); // who
                                                                  //will recieve the message
    var ozMessageData = encodeURIComponent(document.getElementById("messagetext").value);
        //data of the message

    //we make the URL to the correct format for Ozeki NG SMS Gateway Server
    createdURL = ozSURL + ":" + ozSPort + "/httpapi";
    parameters = "action=sendMessage" +
        "&username=" + ozUsername + "&password=" + ozPassw + "&messageType=" +
        ozMessageType + "&recipient=" + ozRecipient + "&messageData=" + ozMessageData;

    ...
}
...
            

Step 3: Sending a request to the SMS Gateway and receiving the answer 
In the code you send a request to the Ozeki NG - SMS Gateway Server with the data of the message. It will create an SMS and send it to the recipient (mobile user) using a GSM modem/phone (if the given data is correct) and send you the result. 
You create a request to the Ozeki NG - SMS Gateway Server at the URL created above. When it is done, you will receive a response from the Ozeki NG - SMS Gateway Server. The information will be retrieved from it and shown to the Internet user. 
(Because of permission rights some exceptions have to be handled.) 

smssend.js
...
function sendRequest()
{
    xmlHttp = GetXmlHttpObject(); //create the object with which we will send
                                  //the request and receive the response

    ...

    try
    {
        xmlHttp.onreadystatechange = showResponse; //set property onreadystatechange
                                                   //on that function that we
                                                   //would like to run when
                                                   //response will be received

        if (navigator.appName == "Netscape")
        {
            try
            {
                //if we haven't got privilege then XMLHttpRequest.open will rise exception
                //netscape.security.PrivilegeManager.enablePrivilege("UniversalPreferencesRead");
                netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");
            }
            catch (e)
            {
                alert(e);
            }
        }

        xmlHttp.open("POST", createdURL, true);
        //if communication between our client and the server is slow, we inform the user about
        //we are doing something:
        document.getElementById("responseText").innerHTML = "Request is under processing...";
        xmlHttp.send(parameters); //we send the request
    }
    catch(e)
    {
        if (navigator.appName == "Netscape")
        {
            alert(e);
        }
        else
        {
            alert(e.description);
        }
    }
}
...
            


If the state of the xmlHttp object changes, the showResponse() function will be run. The ideal state is 4 (meaning that the request is complete). If xmlHttp.responseText is empty, the Ozeki NG - SMS Gateway Server is not running. Otherwise the response text will be written. 

smssend.js
...
function showResponse()
{
    if (xmlHttp.readyState == 4)
    {//state 4 means request is complete
        if (xmlHttp.responseText == "")
        {//if response text is empty, the Ozeki NG SMS Gateway Server is not running
            document.getElementById("responseText").innerHTML =
                                      "Ozeki NG SMS Gateway Server is not running!";
        }
        else
        {//the response text on div responseText will be written
            document.getElementById("responseText").innerHTML = xmlHttp.responseText;
        }
    }
}
...
            

Summary

In the article it has been explained how you can add SMS functionality to your website by using the downloadable AJAX example code. You can freely use and modify that script. Using AJAX scripts (and the Ozeki NG - SMS Gateway Server) you can create a lot of useful services (e.g.: you can add SMS functionality to a website or a corporate Intranet, create automated SMS notifications, increase website security by adding SMS login, etc.).

Frequently asked questions

Question: How can I send the same message to different phone numbers? 
Answer: Separate the phone numbers with the comma character (,). 
   For example: 
   
...
var ozRecipient = encodeURIComponent("+441234567,+447654321");
...


Question: How can I send different message types? 
Answer: For example a Wap push message: 
   
...
var ozMessageType = "SMS:WAPPUSH"; //change the message type 
... 
var messageText = "<si>" + 
  "<indication href="http://target_address" action="signal-high" >" + 
  "text of description" + 
  "</indication>" + 
  "</si>"; 
var ozMessageData = encodeURIComponent(messageText);
...

action can be: signal-high, signal-medium, signal-low, signal-none, signal-delete 

Question: Can I run the AJAX script on a computer different from the one running the Ozeki NG - SMS Gateway Server? 
Answer: Yes, you can. In the script you have to set the URL and the port number of the computer running the Ozeki NG - SMS Gateway Server. 

Question: Can I set the phone number so that the recipient can see where the sms comes from? 
Answer: Yes, you can. In the script you have to set an originator field and include it in the URL string you have created. It works only if you have IP SMS connection. 
   
...
function sendRequest()
{
    ...

    var createdURL = ""; //this will be sent to Ozeki NG SMS Gateway Server...
    var parameters = ""; //...together with the parameters
    var ozSURL = "http://127.0.0.1"; //URL where Ozeki NG SMS Gateway Server is running
    var ozSPort = "9501"; //Port number on which Ozeki NG SMS Gateway Server is listening to
    var ozUsername = encodeURIComponent("admin"); //Username who can log in to Ozeki NG SMS Gateway Server
    var ozPassw = encodeURIComponent("abc123"); //the user's password
    var ozOriginator = encodeURIComponent("+449998887");
                                                  //originator of the message
    
    var ozMessageType = "SMS:TEXT"; //type of the message
    var ozRecipient = encodeURIComponent(document.getElementById("recipient").value); // who
                                                                         //will recieve the message
    var ozMessageData = encodeURIComponent(document.getElementById("messagetext").value);
        //data of the message

    //we make the URL to the correct format for Ozeki NG SMS Gateway Server
    createdURL = ozSURL + ":" + ozSPort + "/httpapi";
    parameters = "action=sendMessage" +
        "&username=" + ozUsername + "&password=" + ozPassw +
        "&originator=" + ozOriginator + 
        "&messageType=" + ozMessageType + "&recipient=" + ozRecipient +
        "&messageData=" + ozMessageData;

    ...
}
...
