### ISSUE TITLE
Research about generating a random code using PHP & JavaScript

### ISSUE THREAD

**Issue by catherineunciano** [IT3A-2016/Paper-Icebergs#21]

**Comment by Nhelie** [comment]
link: http://www.plus2net.com/javascript_tutorial/math-random.php

<html>

<head>

<title>(Type a title for your page here)</title>



<script type="text/javascript"> 

function generate(){

var my_num=Math.random();

document.f1.t1.value=(my_num*11);q
document.f1.t2.value=Math.floor(my_num*11);q
}

</script>



</head>

<body >

<form name=f1>

Random number after multiplying with 11

<input type=text name=t1>

<br>After taking the floor value 

<input type=text name=t2>



<input type=button value='Display' onClick='generate()';>

</form>



</body>

</html>

link: http://www.the-art-of-web.com/javascript/random/

**Comment by catherineunciano** [comment]
http://www.w3schools.com/PHP/func_math_rand.asp
PHP rand() Function

<?php
echo(rand() . "<br>");
echo(rand() . "<br>");
echo(rand(10,100));
?>

**Comment by catherineunciano** [comment]
http://www.mediacollege.com/internet/javascript/number/random.html

How to Create Random Numbers & Characters

This page shows you how to create a random sequence of numbers and/or text. The function which generates the random string can be called from any event handler - the example below uses a button.

 Create Random String   
Step 1
Add the following code to your head:

<script language="javascript" type="text/javascript">
function randomString() {
	var chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";
	var string_length = 8;
	var randomstring = '';
	for (var i=0; i<string_length; i++) {
		var rnum = Math.floor(Math.random() * chars.length);
		randomstring += chars.substring(rnum,rnum+1);
	}
	document.randform.randomfield.value = randomstring;
}
</script>
Variables to set:

chars - The random string will be created from these characters.
string_length - The length of the random string.
Step 2
Use the following code for your text field and button:

<form name="randform">
<input type="button" value="Create Random String" onClick="randomString();">&nbsp;
<input type="text" name="randomfield" value="">
</form>
