### ISSUE TITLE
UI design for log-in for website

### ISSUE THREAD

**Issue by catherineunciano** [IT3A-2016/Paper-Icebergs#23]

**Comment by giomigueltada** [comment]
![gio.png](https://zube.io/files/IT3A-2016/24fbe982565a1c178d17511c22cc0e7e.png)

**Comment by catherineunciano** [comment]
I suggest try choosing color schemes over the FAITH Website, FAITH itself, the student portal, the campus++, the timefree innovations, and the qmobile.
