### ISSUE TITLE
UI design for sign-up for website

### ISSUE THREAD

**Issue by catherineunciano** [IT3A-2016/Paper-Icebergs#24]

**Comment by Nhelie** [comment]
![signup design.jpg](https://zube.io/files/IT3A-2016/35120fcf40c26df657c0115571447644.jpeg)

**Comment by Nhelie** [comment]
![signup design.jpg](https://zube.io/files/IT3A-2016/7465d432bc3a5d742a7c5ecfb1c21541.jpeg)
