### ISSUE TITLE
Test if the sign-up page is functioning

### ISSUE THREAD

**Issue by catherineunciano** [IT3A-2016/Paper-Icebergs#37]

**Comment by catherineunciano** [comment]
![signup1.jpg](https://zube.io/files/IT3A-2016/14020b117cb2fa4980f36252e150f981.jpeg)

If the registration gets successful, you'll see this in the address bar while if not, the page gets refreshed.

**Comment by Nhelie** [comment]
![222.png](https://zube.io/files/IT3A-2016/e56dc644a21ff82157a449bc85a8d399.png)
![111.png](https://zube.io/files/IT3A-2016/beea6de790b8a6ba12844118f882f6ff.png)
